#!/usr/bin/env bash
# Install nginx and configure it to listening on port 80
# Print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'HELLO WORLD!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
