#!/usr/bin/env bash
# Fix nginx listening on port 80
# Go to sites-enabled folder for Nginx
cd /etc/nginx/sites-enabled/ || exit;
# Delete the default file
rm default;
# Create symbolic link to the default file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
